### ISSUE TITLE
"Page Source"  link is broken

### ISSUE THREAD

**Issue by dheepakg** [pyviz/pyviz.org#57]
In [https://pyviz.org/](https://pyviz.org/), the footer contains `Page source` this is URL is broken, redirected to `Page not found` error.

**Comment by jbednar** [comment]
Thanks! We'll have to track down where that gets generated from.

**Comment by dheepakg** [comment]
The pyviz site is built on nbsite. I feel the 'Page Source' is coming from [index.html of pyviz-dev/website](https://github.com/pyviz-dev/website/blob/a309971658141c8b67894d82a9ab83ce21242406/index.html#L99). So, we need to have a folder named _sources and index.rst.txt ?

**Comment by ceball** [comment]
@dheepakg, are you interested in fixing this in nbsite?

Below is some speculation - would need to be verified...

I think pyviz.org's website build job's log shows `_sources` being deliberately removed: 
```
[...]
writing output... [100%] tutorials/index
generating indices...  genindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 4 warnings.
The HTML pages are in builtdocs.
Removing files from: /home/travis/build/pyviz/pyviz.org/builtdocs
removing .doctrees
removing _sources  <------------ HERE
Copying json blobs (used for holomaps) from /home/travis/build/pyviz/pyviz.org/doc to builtdocs
Copying examples assets from /home/travis/build/pyviz/pyviz.org/examples/assets to builtdocs/assets
[...]
```
(https://travis-ci.org/pyviz/pyviz.org/jobs/657893376#L809)

That seems like a mistake, right?

As you point out, the problem comes from nbsite: 

```
for folder in (".doctrees", "_sources"):
    d = os.path.join(htmldir,folder)
    try:
        if dry_run:
            print("would remove", folder)
        else:
            print("removing", folder)
            shutil.rmtree(d)
    except:
        pass
```

(https://github.com/pyviz-dev/nbsite/blob/master/scripts/nbsite_cleandisthtml.py#L32)

It's a shame nobody wrote a note saying why that stuff is being removed.

Could we just delete lines 32-41?

While you're at it, why not delete lines 43-52 too? (No idea what that block is supposed to be doing :) )

The commit history shows people chipping away at that file...but maybe you could finally delete the whole file and then not call it all (https://github.com/pyviz-dev/nbsite/blob/master/nbsite/cmd.py#L84)? That would be great if possible. Looks like the last part of the file is removing (potentially large?) evaluated notebook files from the html directory. That part might need some thought - maybe they shouldn't be ending up in the output html directory at all in the first place?

**Comment by dheepakg** [comment]
@ceball Yea I'm interested in fixing this. 

We can remove lines [32 - 52](https://github.com/pyviz-dev/nbsite/blob/abb56c2a5b1348c97c2b1f2072632dc8a74eba00/scripts/nbsite_cleandisthtml.py#L32).

Firstly, I'll remove lines 32-52. Then, will make changes in [cmd.py](https://github.com/pyviz-dev/nbsite/blob/master/nbsite/cmd.py) file.

I'm yet to build the site in my local machine. Will update you over the weekend, on my progress.

**Comment by dheepakg** [comment]
@ceball Could you help me with the docs for setting up nbsite. I couldn't find docs.

PS: Should we move/open this issue under nbsite repo?

**Comment by ceball** [comment]
> Could you help me with the docs for setting up nbsite. I couldn't find docs.

nbsite, which is a project to enable documentation, has itself always had no/minimal/poor documentation :(

Docs: https://nbsite.holoviz.org/ (but I suspect they might just be frustrating).

There are examples of nbsite in use, e.g. for the pyviz.org website itself. The link to travis above (in an earlier comment) will take you to a build. There, you see the github repo being cloned, and then nbsite being invoked via `doit build_website`, for which you can see the commands at https://github.com/pyviz/pyviz.org/blob/master/dodo.py#L39:

![Screenshot from 2020-03-06 14-45-18](https://user-images.githubusercontent.com/1929/76093598-24d8d500-5fb9-11ea-8720-9cd3c32dfa7b.png)

I'm sure I've missed stuff out. If the nbsite developer docs are missing (as I suspect they are), it would be great to update them even just with notes you take as you go.

Good luck :) Feel free to ask questions as you go.

> Should we move/open this issue under nbsite repo?

Sure, please open an issue there. We unfortunately can't move issues between gh orgs (as far as I'm aware, anyway).

**Comment by jbednar** [comment]
Closing as it's covered on nbsite.
