### ISSUE TITLE
handle packages with multiple conda recipes 

### ISSUE THREAD

**Issue by mdeff** [pyviz/pyviz.org#61]
Some packages have multiple recipes. For example, matplotlib has at least three popular conda recipes:
* [defaults/matplotlib](https://anaconda.org/anaconda/matplotlib) with ~490k downloads
* [conda-forge/matplotlib](https://anaconda.org/conda-forge/matplotlib) with ~5.8M downloads
* [conda-forge/matplotlib-base](https://anaconda.org/conda-forge/matplotlib-base) with ~3.0M downloads
* and [more](https://anaconda.org/search?q=matplotlib)

Those should be taken into account for the download statistics.

**Comment by jbednar** [comment]
Definitely!  My own packages all suggest using our custom conda channel to get the latest versions, and none of those get counted either right now.

Matplotlib is a special case here, because I believe they only split into separate "matplotlib" and "matplotlib-base" packages within the past couple of years, and so they have lots of older versions that weren't split.  If we simply pooled across all of the above channels (plus defaults/matplotlib-base), we'd be double counting, because every download of current `matplotlib` versions also forces a download of `matplotlib-base` (but not vice versa).  Once no one is using older matplotlib versions (which may have already happened?) we could just count matplotlib-base, but for now it seems safer to count only the matplotlib downloads directly, ignoring matplotlib-base.  It's true that can fail to count deliberate downloads of matplotlib-base, but I'd guess that most such uses will be indirect downloads via a library where mpl is embedded (e.g. Pandas), and in those cases it's not clear whether the user even wanted or used the plotting facilities. Things like that can drive the "core" library to get downloads vastly larger than derived libraries in ways that don't necessarily reflect actual usage or interest. 

All told, for matplotlib in particular, I think the current default of counting defaults/matplotlib plus conda-forge/matplotlib is about as accurate as we can get, and most comparable to the other libraries listed. But for other libraries with significant downloads outside of defaults and conda-forge, we should try to get those numbers included...

**Comment by jbednar** [comment]
I forget the details, but a couple of months ago we did a review of the overall conda downloads for these projects compared to the numbers showing up in the counts (ignoring `-base` issues as above) and didn't find any discrepancies, so I'm going to close this issue, but people should open new issues if they ever find a significant source of downloads not counted in the stats.
