### ISSUE TITLE
Pyviz Tools page not updating

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyviz/pyviz.org#83]
https://pyviz.org/tools.html

The numbers below are +6month old

![image](https://user-images.githubusercontent.com/42288570/96469686-ca317800-122d-11eb-84fe-5d0cff3f908d.png)

**Comment by adyork** [comment]
Stars, Contributors, Downloads License all are broken it looks like?

Chrome Version 86.0.4240.111 (Official Build) (64-bit)
https://pyviz.org/tools.html

![image](https://user-images.githubusercontent.com/9537357/97218744-7845a080-179f-11eb-95ff-ab484fae1b94.png)

**Comment by jbednar** [comment]
That's a different problem.  The ones that are out of date are a bug, due to broken links and issues with our CI. The broken images like that are just due to throttling at the badge providers, where they put limits on how many badges a user can request in a given amount of time. Usually those limits aren't reached, but with a badge-heavy page like the tools page, the badge providers stop answering our queries. The badges are cached, though (_supposed_ to update once per month), so if you refresh the page you'll usually see the missing ones appear.  There may be some fancy solution for this issue, but if so I don't know it...

**Comment by jbednar** [comment]
Ok, CI should now be fixed, with up to date numbers!
